baseURL = "http://forestaa.github.io/blog"
languageCode = "ja-jp"
title = "存在と一意性の証明"
theme = "whiteplain"
publishDir = "docs"

pygmentsUseClasses = true
hasCJKLanguage = true
summaryLength = 200

[[menu.main]]
  name = "Tags"
  identifier = "tags"
  url = "/tags/"
  weight = 2
[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/archives/"
  weight = 3
[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 4
